replicaCount: 3

image:
  repository: ghcr.io/dogrueymen/devops-internship-case
  tag: "1.0.0-eb95351"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

livenessProbe:
  path: /healthz
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  path: /readyz
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

ingress:
  enabled: true
  className: nginx
  host: api.example.com
  paths:
    - path: /
      pathType: Prefix
